// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin-dashboard": {
    params: {};
  };
  "/event-manager": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/admin-dashboard" | "/event-manager" | "/register" | "/login" | "/*";
  };
  "routes/[admin-dashboard]._index.jsx": {
    id: "routes/[admin-dashboard]._index";
    page: "/admin-dashboard";
  };
  "routes/[event-manager]._index.jsx": {
    id: "routes/[event-manager]._index";
    page: "/event-manager";
  };
  "routes/[register]._index.jsx": {
    id: "routes/[register]._index";
    page: "/register";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};